### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by xlar54** [chronicle95/SimpleBasic#1]
Heya, just wanted to thank you for this code.  Im going to use it as the basis for a bare metal raspberry pi BASIC implementation.  There are indeed things to fix, but I will aim to keep the files independent, so that when I am done, you can have the code back and improve on your instance.

**Comment by chronicle95** [comment]
Yeah, sure. The project is pretty much stalled at this point so I'm glad somebody made use of it :)
